package com.class06;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Alert {

	public static void main(String[] args)  {
//		1) Launch new Browser
//
//	2) Open URL “http://toolsqa.com/automation-practice-switch-windows/”
//
//	3) Click on Button “Alert Box”, it will open a Pop Up Window generated by JavaScript
//
//	4) Switch to Alert window (Use ‘SwitchTo()Alert() command)
//
//	5) Close the Pop Up Window (Use Accept command)

		
		System.setProperty("webdriver.chrome.driver", "/Users/newowner/Selenium/chromedriver");
		WebDriver driver = new ChromeDriver();
		
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		 
        // Launch the URL
		driver.get("http://toolsqa.com/automation-practice-switch-windows/");
		driver.findElement(By.name("Alert Box")).click();
		 
        // Switch to JavaScript Alert window
//
		 org.openqa.selenium.Alert alert = driver.switchTo().alert();
//		
        alert.accept();
		
	}

}
